// <auto-generated />
namespace Ibushak.Productos.Core.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AjusteCampoActualizacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjusteCampoActualizacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201708021908461_AjusteCampoActualizacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
